{ pkgs, ... }:

{
  programs.tmux = {
    enable = true;
    prefix = "C-a";
    mouse = true;
    escapeTime = 0;
    historyLimit = 10000;
    terminal = "screen-256color";
    keyMode = "vi";

    plugins = with pkgs.tmuxPlugins; [
      # Replaces the hand-written is_vim / C-hjkl if-shell block from the old
      # tmux.conf — same behaviour, kept up to date upstream, and it also
      # handles the copy-mode-vi side that the old config duplicated by hand.
      vim-tmux-navigator
      sensible
      yank
    ];

    extraConfig = ''
      # ── splits inherit the current pane's path ──────────────────────────
      bind '"' split-window -c "#{pane_current_path}"
      bind %   split-window -h -c "#{pane_current_path}"
      bind c   new-window -c "#{pane_current_path}"
      bind |   split-window -h
      bind \\  split-window -h -c "#{pane_current_path}"
      bind _   split-window
      bind -   split-window -c "#{pane_current_path}"

      # NOTE: master has `bind-key -n C-m ... send-keys C-l`. C-m *is* Enter on
      # every terminal that doesn't send CSI-u, so that binding makes Return
      # stop working inside tmux, and both if-shell branches are identical
      # anyway. vim-tmux-navigator above already covers C-hjkl in and out of
      # vim, so it's left out here. Uncomment if you really did want it:
      # bind-key -n C-m send-keys C-l

      # ── statusline: tokyonight_moon ─────────────────────────────────────
      # Was ~/.tmuxline.snapshot (gruvbox, generated by tmuxline.vim). Now it
      # matches wezterm / neovim / zellij, which are all tokyonight_moon.
      set -g status "on"
      set -g status-justify "left"
      set -g status-left-length "100"
      set -g status-right-length "100"
      set -g status-style "none,bg=#2f334d"
      set -g status-left-style "none"
      set -g status-right-style "none"
      set -g message-style "fg=#c8d3f5,bg=#3b4261"
      set -g message-command-style "fg=#c8d3f5,bg=#3b4261"
      set -g pane-border-style "fg=#3b4261"
      set -g pane-active-border-style "fg=#82aaff"

      setw -g window-status-separator ""
      setw -g window-status-style "none,fg=#828bb8,bg=#2f334d"
      setw -g window-status-activity-style "underscore,fg=#c8d3f5,bg=#2f334d"

      set -g status-left "#[fg=#1b1d2b,bg=#82aaff,bold] 🐧 #[fg=#82aaff,bg=#2f334d,nobold,nounderscore,noitalics]"
      set -g status-right "#[fg=#3b4261,bg=#2f334d,nobold,nounderscore,noitalics]#[fg=#c8d3f5,bg=#3b4261] #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null) #[fg=#82aaff,bg=#3b4261,nobold,nounderscore,noitalics]#[fg=#1b1d2b,bg=#82aaff,bold] #h "
      setw -g window-status-format "#[fg=#2f334d,bg=#2f334d,nobold,nounderscore,noitalics]#[default] #I  #W #[fg=#2f334d,bg=#2f334d,nobold,nounderscore,noitalics]"
      setw -g window-status-current-format "#[fg=#2f334d,bg=#3b4261,nobold,nounderscore,noitalics]#[fg=#c8d3f5,bg=#3b4261,bold] #I  #W #[fg=#3b4261,bg=#2f334d,nobold,nounderscore,noitalics]"
    '';
  };
}
