{ pkgs, ... }:

{
  programs.tmux = {
    enable = true;
    prefix = "C-a";
    mouse = true;
    escapeTime = 0;
    historyLimit = 10000;
    terminal = "screen-256color";
    keyMode = "vi";

    plugins = with pkgs.tmuxPlugins; [
      # Replaces the hand-written is_vim / C-hjkl if-shell block from the old
      # tmux.conf — same behaviour, kept up to date upstream.
      vim-tmux-navigator
      sensible
      yank
    ];

    extraConfig = ''
      # ── splits inherit the current pane's path ──────────────────────────
      bind '"' split-window -c "#{pane_current_path}"
      bind %   split-window -h -c "#{pane_current_path}"
      bind c   new-window -c "#{pane_current_path}"
      bind |   split-window -h
      bind \\  split-window -h -c "#{pane_current_path}"
      bind _   split-window
      bind -   split-window -c "#{pane_current_path}"

      # ── statusline (was ~/.tmuxline.snapshot, generated by tmuxline.vim) ─
      set -g status "on"
      set -g status-justify "left"
      set -g status-left-length "100"
      set -g status-right-length "100"
      set -g status-style "none,bg=#3c3836"
      set -g status-left-style "none"
      set -g status-right-style "none"
      set -g message-style "fg=#a89984,bg=#504945"
      set -g message-command-style "fg=#a89984,bg=#504945"
      set -g pane-border-style "fg=#504945"
      set -g pane-active-border-style "fg=#a89984"

      setw -g window-status-separator ""
      setw -g window-status-style "none,fg=#a89984,bg=#3c3836"
      setw -g window-status-activity-style "underscore,fg=#a89984,bg=#3c3836"

      set -g status-left "#[fg=#282828,bg=#a89984] 🐧 #[fg=#a89984,bg=#3c3836,nobold,nounderscore,noitalics]"
      set -g status-right "#[fg=#a89984,bg=#3c3836,nobold,nounderscore,noitalics]#[fg=#282828,bg=#a89984]  #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD) "
      setw -g window-status-format "#[fg=#3c3836,bg=#3c3836,nobold,nounderscore,noitalics]#[default] #I  #W #[fg=#3c3836,bg=#3c3836,nobold,nounderscore,noitalics]"
      setw -g window-status-current-format "#[fg=#3c3836,bg=#504945,nobold,nounderscore,noitalics]#[fg=#a89984,bg=#504945] #I  #W #[fg=#504945,bg=#3c3836,nobold,nounderscore,noitalics]"
    '';
  };
}
